# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='chart',
            name='timestamp',
            field=models.DateTimeField(verbose_name='date publish'),
        ),
    ]
