# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='la',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='lo',
            field=models.FloatField(default=0),
        ),
    ]
