# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.DecimalField(decimal_places=3, max_digits=5)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
